{{- range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-user-{{ .access_key }}
data:
  CONSOLE_ACCESS_KEY: {{ .access_key | b64enc }}
  CONSOLE_SECRET_KEY: {{ .secret_key | b64enc }}
type: Opaque
{{- end }}