---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator-webhook-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb-operator-webhook
  policyTypes:
    - Ingress
  ingress:
    - ports:
      - protocol: TCP
        port: 9443
