{{- if .Values.networkPolicy -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator-to-pools-egress
spec:
  policyTypes:
    - Egress
  egress:
    - ports:
      - protocol: TCP
        port: 9000
      - protocol: TCP
        port: 9090
      - protocol: TCP
        port: 80
{{- end }}
