
# -- Name of the mariadb instance
name: mariadb

# -- Application username to assign to the instance
username: mariadb

# -- Application database name
database: mariadb

# -- Port to expose the service on
port: 3306

storage:
  # -- Amount of storage to assign to the PVC
  size: 1Gi
  # -- Storage class name
  storageClassName: ''

service:
  # -- Service type
  type: ClusterIP

metrics:
  # -- Whether to enable Prometheus metrics
  enabled: true


rootPasswordSecret:
  # -- Name of the secret to store the root password
  name: mariadb-root
  # -- Key within the secret
  key: password
  # -- Whether to autogenerate the password
  generate: true
userPasswordSecret:
  # -- Name of the secret to store the root password
  name: mariadb-password
  # -- Key within the secret
  key: password
  # -- Whether to autogenerate the password
  generate: true
