apiVersion: v2
name: onetimesecret
description: A Helm chart for deploying OneTimeSecret

type: application

version: 0.1.0

dependencies:
  - name: redis
    version: ~19.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

appVersion: "v0.15.1"
