---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.name }}
spec:

  username: {{ .Values.username }}
  database: {{ .Values.database }}

  port: {{ .Values.port }}

  {{- with .Values.storage }}
  storage:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.rootPasswordSecret }}
  rootPasswordSecretKeyRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.userPasswordSecret }}
  passwordSecretKeyRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
