{{- if .Values.networkPolicy -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-smtp-to-internet-egress
spec:
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          {{- with .Values.networkPolicy.deniedExternalIPs }}
          except:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      ports:
      - protocol: TCP
        port: {{ .Values.smtp.smarthost.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pods-to-smtp-ingress
spec:
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector: {}
      ports:
      - protocol: TCP
        port: 25
{{- end }}