---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onetimesecret.fullname" . }}-app-config
  labels:
    {{ include "onetimesecret.labels" . | nindent 4 }}
data:
  config: |
    ---
    :site:
      :host: <%= ENV['HOST'] || 'localhost:3000' %>

      :domain: localhost
      :ssl: false

      :secret: <%= ENV['SECRET'] || 'CHANGEME' %>

      :authentication:
        :enabled: {{ .Values.authentication.enabled | default false }}

        :signup: {{ .Values.authentication.signup | default false }}

        :signin: {{ .Values.authentication.signin | default false }}

        :autoverify: {{ .Values.authentication.autoverify | default false }}
    :redis:
      :uri: <%= ENV['REDIS_URL'] || 'redis://CHANGEME@127.0.0.1:6379/0' %>
    :colonels:
      # Email addresses listed below will be granted automatic
      # administrative privileges upon account creation. These
      # accounts will have full control over the system.
      - <%= ENV['COLONEL'] || 'CHANGEME@example.com' %>
    :emailer:
      :mode: <%= ENV['EMAILER_MODE'] || :smtp %>
      :from: <%= ENV['FROM'] || 'CHANGEME@example.com' %>
      :fromname: <%= ENV['FROMNAME'] || 'Jan' %>
      :host: <%= ENV['SMTP_HOST'] || 'localhost' %>
      :port: <%= ENV['SMTP_PORT'] || 587 %>
      :user: <%= ENV['SMTP_USERNAME'] || 'CHANGEME' %>
      :pass: <%= ENV['SMTP_PASSWORD'] || 'CHANGEME' %>
      :tls: <%= ENV['SMTP_TLS'] || true %>
    :mail:
      :truemail:
        # Available validation types: :regex, :mx, :mx_blacklist, :smtp
        :default_validation_type: :regex
        # Required for :smtp validation
        :verifier_email: <%= ENV['VERIFIER_EMAIL'] || 'CHANGEME@example.com' %>
        #:verifier_domain: <%= ENV['VERIFIER_DOMAIN'] || 'example.com' %>
        #:connection_timeout: 2
        #:response_timeout: 2
        #:connection_attempts: 3
        #:validation_type_for:
        #  'example.com': :regex
        #
        # Truemail will only validate email addresses that match the
        # domains listed in :allowed_domains. If the domain is not
        # listed, the email address will always be considered invalid.
        :allowed_domains_only: false
        #
        # Email addresses in this list will always be valid.
        #:allowed_emails: []
        #
        # Email addresses in this list will always be invalid.
        #:blocked_emails: []
        #
        # Addresses with these domains will always be valid
        #:allowed_domains: []
        #
        # Addresses with these domains will always be invalid
        #:blocked_domains: []
        #
        # Exclude these IP addresses from the MX lookup process.
        #:blocked_mx_ip_addresses: []
        #
        # Name servers to use for MX et al record lookup.
        # Default is CloudFlare, Google, Oracle/OpenDNS servers.
        :dns:
          - 1.1.1.1
          - 8.8.4.4
          - 208.67.220.220
        #:smtp_port: 25
        #
        # End smtp validation after the first invalid response rather than
        # retrying, followed by trying the next server. Can reduce the time
        # time to validate an email address, but may not catch all issues.
        :smtp_fail_fast: false
        #
        # Parse the content of the SMTP error message to determine if the
        # email address is valid. This can be useful for some SMTP servers
        # that don't return exact answers.
        :smtp_safe_check: true
        #
        # Whether to disable the RFC MX lookup flow. When true, only DNS
        # validation will be performed on MX and Null MX records.
        :not_rfc_mx_lookup_flow: false
        #
        # Override default regular expression pattern for email addresses
        # and/or the content in SMTP error messages.
        #:email_pattern: /regex_pattern/
        #:smtp_error_body_pattern: /regex_pattern/
        #
        # Log to the console, a file, or both. The ruby process must have
        # write access to the log file. The log file will be created if it
        # does not exist. Log file rotation is not handled by the app.
        :logger:
          # One of: :error (default), :unrecognized_error,
          # :recognized_error, :all.
          tracking_event: :error
          stdout: true
          # log_absolute_path: '/home/app/log/truemail.log'
    :locales:
      # A list of ISO language codes (e.g., 'en' for English, 'es'
      # for Spanish, etc.). There is a corresponding file in etc/locales
      # with the same name containing the translated text. If it's not
      # selected automatically, users are able to select their preferred
      # language by using the links on the translations page.
      #
      # NOTE: The default locale is the first item.
      - en
      - ar
      - bg
      - ca_ES
      - cn
      - cs
      - da_DK
      - de
      - el_GR
      - en
      - es
      - fr
      - fr_FR
      - he
      - hu
      - it_IT
      - nl
      - pl
      - pt_BR
      - ru
      - sl_SI
      - sv_SE
      - tr
      - vi
    :services:
      :sentry:
        :dsn: <%= ENV['SENTRY_DSN'] || 'CHANGEME' %>
        :enabled: <%= !ENV['SENTRY_DSN'].nil? %>
    :limits:
      # This section defines rate limits for various events per user
      # per a rolling 20 minute period. Each key is an event name
      # and the value is the max count allowed. Changes require
      # restart of the app.
      :create_secret: 1000
      :create_account: 10
      :update_account: 10
      :email_recipient: 50
      :send_feedback: 10
      :authenticate_session: 5
      :homepage: 1000
      :dashboard: 1000
      :failed_passphrase: 5
      :show_metadata: 1000
      :show_secret: 1000
      :burn_secret: 1000
      :destroy_account: 2
      :forgot_password_request: 2
      :forgot_password_reset: 3
      :generate_apikey: 10
    :development:
      :enabled: <%= ['development', 'dev'].include?(ENV['RACK_ENV']) %>
      :debug: <%= ['true', '1', 'yes'].include?(ENV['ONETIME_DEBUG']) %>
      :frontend_host: <%= ENV['FRONTEND_HOST'] || 'http://localhost:5173' %>
