{{- if .Values.mariadb.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-db-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.mariadb.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            {{- include "projectsend.selectorLabels" . | nindent 12 }}
    - ports:
      - protocol: TCP
        port: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-db-egress
spec:
  podSelector:
    matchLabels:
      {{- include "projectsend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Values.mariadb.name }}
    - ports:
      - protocol: TCP
        port: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-smtp
spec:
  podSelector:
    matchLabels:
      {{- include "projectsend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
      - protocol: TCP
        port: 25
{{- end }}
