{{- if .Values.mariadb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-password
  labels:
    {{- include "projectsend.labels" . | nindent 4 }}
data:
  password: {{ .Values.mariadb.password | b64enc }}
{{- end }}
