vaultwarden:
  data:
    # -- Whether to create a PVC
    enabled: true
    # -- Name of the PVC
    name: data
    # -- Size of PVC to create
    size: 1Gi
    # -- Storage Class Name
    class: ''
  # -- URL of the VaultWarden instance
  domain: https://vaultwarden.exmaple.com/
  # -- Whether to allow signups
  signupsAllowed: true
  # -- Limit signups to this domain suffix
  signupDomains: "example.com"
  smtp:
    # -- SMTP server
    host: smtp.example.com
    # -- TLS
    security: "off"
    # -- From address for emails
    from: vaultwarden@example.com
  ingress:
    # -- Whether or not to deploy an Ingress resource
    enabled: true
    # -- Ingress hostname
    hostname: vaultwarden.example.com
    # -- Ingress resource class
    class: "nginx"
    # -- TLS Secret
    tlsSecret: vaultwarden-tls
    # -- Additional annotations for the Ingress resource
    additionalAnnotations:
      cert-manager.io/cluster-issuer: stepca
networkPolicy:
  # -- Whether or not to deploy the NetworkPolicy resource
  enabled: true
  # -- External IP addresses to which Vaultwarden cannot communicate
  deniedExternalIPs:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
